package ui;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;

public class StarterPageGUI {
    private JButton startGameButton;
    private JPanel MainPanel;
    private JPanel PlayerOnePanel;
    private JPanel PlayerTwoPanel;
    private JSpinner pl2_type;
    private JSpinner pl1_type;
    private JTextPane choosePlayerTypeTextPane1;
    private JTextPane choosePlayerTypeTextPane;
    private JSpinner pl1_depth;
    private JTextPane gameTreeDepthTextPane;
    private JTextPane gameTreeDepthTextPane1;
    private JSpinner pl2_depth;
    private JTextPane nameTextPane;
    private JTextArea pl1_name;
    private JTextPane colorTextPane;
    private JSpinner pl1_color;
    private JSpinner pl2_color;
    private JTextPane colorTextPane1;
    private JTextPane nameTextPane1;
    private JTextArea pl2_name;
    private JPanel pane12;
    private JPanel pane11;
    private JPanel pane13;
    private JPanel pane14;
    private JPanel pane21;
    private JPanel pane22;
    private JPanel pane23;
    private JPanel pane24;

    public StarterPageGUI() {


        init();

        pl1_type.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent changeEvent) {
                System.out.println(((JSpinner) changeEvent.getSource()).getValue());
            }
        });
    }

    public void init()
    {
        JMenu type = new JMenu();
        type.add("Human");
        type.add("AI");
        pane12.add(type);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridBagLayout());
        PlayerOnePanel = new JPanel();
        PlayerOnePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(PlayerOnePanel, gbc);
        PlayerOnePanel.setBorder(BorderFactory.createTitledBorder("Player One:"));
        pane11 = new JPanel();
        pane11.setLayout(new GridBagLayout());
        pane11.setPreferredSize(new Dimension(114, 55));
        PlayerOnePanel.add(pane11);
        nameTextPane = new JTextPane();
        nameTextPane.setEditable(false);
        nameTextPane.setText("Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane11.add(nameTextPane, gbc);
        pl1_name = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane11.add(pl1_name, gbc);
        pane12 = new JPanel();
        pane12.setLayout(new GridBagLayout());
        PlayerOnePanel.add(pane12);
        choosePlayerTypeTextPane = new JTextPane();
        choosePlayerTypeTextPane.setEditable(false);
        choosePlayerTypeTextPane.setText("Choose Player Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane12.add(choosePlayerTypeTextPane, gbc);
        pl1_type = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pane12.add(pl1_type, gbc);
        pane13 = new JPanel();
        pane13.setLayout(new GridBagLayout());
        PlayerOnePanel.add(pane13);
        pl1_depth = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pane13.add(pl1_depth, gbc);
        gameTreeDepthTextPane = new JTextPane();
        gameTreeDepthTextPane.setEditable(false);
        gameTreeDepthTextPane.setText("Game Tree Depth");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane13.add(gameTreeDepthTextPane, gbc);
        pane14 = new JPanel();
        pane14.setLayout(new GridBagLayout());
        PlayerOnePanel.add(pane14);
        colorTextPane = new JTextPane();
        colorTextPane.setEditable(false);
        colorTextPane.setText("Color");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane14.add(colorTextPane, gbc);
        pl1_color = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pane14.add(pl1_color, gbc);
        PlayerTwoPanel = new JPanel();
        PlayerTwoPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(PlayerTwoPanel, gbc);
        PlayerTwoPanel.setBorder(BorderFactory.createTitledBorder("Player Two:"));
        pane21 = new JPanel();
        pane21.setLayout(new GridBagLayout());
        pane21.setPreferredSize(new Dimension(114, 55));
        PlayerTwoPanel.add(pane21);
        nameTextPane1 = new JTextPane();
        nameTextPane1.setEditable(false);
        nameTextPane1.setText("Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane21.add(nameTextPane1, gbc);
        pl2_name = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane21.add(pl2_name, gbc);
        pane22 = new JPanel();
        pane22.setLayout(new GridBagLayout());
        PlayerTwoPanel.add(pane22);
        choosePlayerTypeTextPane1 = new JTextPane();
        choosePlayerTypeTextPane1.setEditable(false);
        choosePlayerTypeTextPane1.setText("Choose Player Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane22.add(choosePlayerTypeTextPane1, gbc);
        pl2_type = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pane22.add(pl2_type, gbc);
        pane23 = new JPanel();
        pane23.setLayout(new GridBagLayout());
        PlayerTwoPanel.add(pane23);
        gameTreeDepthTextPane1 = new JTextPane();
        gameTreeDepthTextPane1.setEditable(false);
        gameTreeDepthTextPane1.setEnabled(true);
        gameTreeDepthTextPane1.setText("Game Tree Depth");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane23.add(gameTreeDepthTextPane1, gbc);
        pl2_depth = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pane23.add(pl2_depth, gbc);
        pane24 = new JPanel();
        pane24.setLayout(new GridBagLayout());
        PlayerTwoPanel.add(pane24);
        pl2_color = new JSpinner();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        pane24.add(pl2_color, gbc);
        colorTextPane1 = new JTextPane();
        colorTextPane1.setEditable(false);
        colorTextPane1.setText("Color");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        pane24.add(colorTextPane1, gbc);
        startGameButton = new JButton();
        startGameButton.setText("Start Game");
        startGameButton.setVerticalAlignment(0);
        startGameButton.setVerticalTextPosition(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(startGameButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
